parameters:
- name: configs
  type: string
  default: 'x86,x64'

trigger:
  branches:
   include:
     - main

variables:
 - name: CACHE_MODE
   value: $(CACHE_MODE_VAL)

jobs:
- ${{ if contains(parameters.configs, 'x86') }}:
  - job: x86
    steps:
    - script: echo Building x86...
- ${{ if contains(parameters.configs, 'x64') }}:
  - job: x64
    steps:
    - script: echo Building x64...
- ${{ if contains(parameters.configs, 'arm') }}:
  - job: arm
    steps:
    - script: echo Building arm...