# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
   include:
     - main
     - test
  paths:
   exclude:
     - README.md
     - azure-pipelines.yml
    
pr:
  branches:
    include:
      - main
  paths:
    exclude:
     - README.md
     - azure-pipelines.yml

pool:
  vmImage: ubuntu-latest

resources:
 repositories:
   - repository: mypythonrepo
     endpoint: sudarsesh
     type: github
     name: sudarsesh/python-multi-repo-1

steps:

- checkout: self

- bash: ls -l
  displayName: print the contents of workspace
  
- script: python3 hello.py
  displayName: 'Run hello.py'

- checkout: mypythonrepo
  displayName: checkout sudarsesh/python-multi-repo-1

- script: python3 python-multi-repo1/external.py
  displayName: run external.py from python-multi-repo1

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '/tmp/test_logs'
    artifactType: 'pipeline'
    artifactName: 'hello_artifacts'
  displayName: 'Archive log files'
