# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
   include:
     - main
     - test
  paths:
   exclude:
     - README.md
     - azure-pipelines.yml
    
pr:
  branches:
    include:
      - main
  paths:
    exclude:
     - README.md
     - azure-pipelines.yml

pool:
  vmImage: ubuntu-latest

steps:
- script: python3 hello.py
  displayName: 'Run hello.py'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '/tmp/test_logs'
    artifactType: 'pipeline'
    artifactName: 'hello_artifacts'
  displayName: 'Archive log files'
