parameters:
- name: configs
  type: string
  default: 'x86,x64'
- name: 'jobFilters'
  type: object
  default: ''
- name: 'buildOptions'
  type: string
  default: 'SONIC_CONFIG_BUILD_JOBS=1'
- name: 'preSteps'
  type: stepList
  default: []
- name: 'postSteps'
  type: stepList
  default: []
- name: 'jobGroups'
  type: object
  default: ''

trigger:
  branches:
   include:
     - main

jobs:
- ${{ if contains(parameters.configs, 'x86') }}:
  - job: x86
    steps:
    - script: echo Building x86...
- ${{ if contains(parameters.configs, 'x64') }}:
  - job: x64
    steps:
    - script: echo Building x64...
- ${{ if contains(parameters.configs, 'arm') }}:
  - job: arm
    steps:
    - script: echo Building arm...

- job: importing my-first-template
  template: testingazurepipelines/.azure-pipelines/first-template.yml
  parameters:
    preSteps: ${{ parameters.preSteps }}
    postSteps: ${{ parameters.postSteps }}
