parameters:
  - name: 'preSteps'
    type: stepList
    default: []
  - name: "postSteps"
    type: stepList
    default: []
   
jobs:
  - job:
    displayName: first template job
    steps:
      - ${{ parameters.preSteps }}
      - bash: echo "inside first-template"
      - ${{ parameters.postSteps }}
