parameters:
  - name: 'preSteps'
    type: stepList
    default: []
  - name: "postSteps"
    type: stepList
    default: []
  - name: "CACHE_MODE"
    type: string
    default: "rwcache"
   
jobs:
  - job:
    displayName: first template job
    steps:
      - ${{ parameters.preSteps }}
      - bash: echo "inside first-template"
      - ${{ parameters.postSteps }}
      - bash: echo "CACHE_MODE=$(CACHE_MODE)"
